"""Add new field to table

Revision ID: 48c1be2d6917
Revises: fddba73a6491
Create Date: 2023-05-11 19:25:17.570234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c1be2d6917'
down_revision = 'fddba73a6491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppy', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppy', 'id')
    # ### end Alembic commands ###
